name: CI
on:
  - push
  - pull_request
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: npx prettier --check .
      - name: Build
        run: pnpm build
