# This is for publishing documentation manually.
# During release `publish-release.yaml` publishes docs automatically.
name: Publish Documentation

on:
  workflow_dispatch:

jobs:
  publish_docs:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-and-build

      - name: Build docs
        run: pnpm run docs:build

      - name: Deploy documentation
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tutorialkit-docs-page
          workingDirectory: 'docs/tutorialkit.dev'
          directory: dist
